### ISSUE TITLE
How to improve the model

### ISSUE THREAD

**Issue by sekhwal** [vappiah/Machine-Learning-Tutorials#1]
Hi,
It is fantastic. I am wondering if the model is not good. How we can improve the prediction?

**Comment by vappiah** [comment]
@sekhwal There are a number of ways to improve the model.

You can perform hyper parameter tuning 
You can also use different models and see the one which gives the best performance.

This [tutorial ](https://youtu.be/Q1AFQ9GZ_kc)I made may be useful for you. In the tutorial I compare the performance of three models
